# In the future move docker compose to a single project and instead of building image with api, upload docker image to docker hub
# So this compose will be a central file with all the api microservices that will be pulled form docker hub
# To each project add github workflow that after release (maybe after each push to master) a docker image will be build and pushed to docker hub
version: "3.9"
services:
  api:
    build: .
    ports:
      - "5000:80"
      - "5001:443"
    environment:
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_Environment=Development
      - PoliticalPartiesApi_ConnectionStrings__DefaultConnection=Server=db,1433;Database=politicz-politicians-and-parties;User Id=sa;Password=Password12345;TrustServerCertificate=True;
      - PoliticalPartiesApi_ConnectionStrings__MasterConnection=Server=db,1433;Database=master;User Id=sa;Password=Password12345;TrustServerCertificate=True;
    depends_on:
      - db

  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: Password12345
    ports:
      - "1433:1433"
