name: Politicians and parties workflow

on:
  push:
  pull_request:
    branches: [ main ]

jobs:
  call-workflow:
    uses: Politi-cz/centralized-configuration/.github/workflows/build_and_test_dot_net_7.yaml@main
